# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SMSObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, phone_number: str=None, message_body: object=None):  # noqa: E501
        """SMSObject - a model defined in Swagger

        :param phone_number: The phone_number of this SMSObject.  # noqa: E501
        :type phone_number: str
        :param message_body: The message_body of this SMSObject.  # noqa: E501
        :type message_body: object
        """
        self.swagger_types = {
            'phone_number': str,
            'message_body': object
        }

        self.attribute_map = {
            'phone_number': 'phoneNumber',
            'message_body': 'messageBody'
        }
        self._phone_number = phone_number
        self._message_body = message_body

    @classmethod
    def from_dict(cls, dikt) -> 'SMSObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SMSObject of this SMSObject.  # noqa: E501
        :rtype: SMSObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this SMSObject.


        :return: The phone_number of this SMSObject.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this SMSObject.


        :param phone_number: The phone_number of this SMSObject.
        :type phone_number: str
        """
        if phone_number is None:
            raise ValueError("Invalid value for `phone_number`, must not be `None`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def message_body(self) -> object:
        """Gets the message_body of this SMSObject.


        :return: The message_body of this SMSObject.
        :rtype: object
        """
        return self._message_body

    @message_body.setter
    def message_body(self, message_body: object):
        """Sets the message_body of this SMSObject.


        :param message_body: The message_body of this SMSObject.
        :type message_body: object
        """
        if message_body is None:
            raise ValueError("Invalid value for `message_body`, must not be `None`")  # noqa: E501

        self._message_body = message_body
